Sandraschumann
robotont/robotont pull request #1
Opened 2020-02-06 16:45 UTC by sandra-schumann

A quick and dirty quick start guide for the README file.

2020-02-06 18:01 UTC, RValner requested changes
Minor fixes needed, refer to the comments.

2020-02-06 18:01 UTC, RValner commented on README.md
> +## Quick Start Guide
Maybe rename it to "Setting up the real robot" or something

2020-02-06 18:01 UTC, RValner commented on README.md
> +- Launch a demo program using the command `roslaunch robotont_teleop teleop_keyboard.launch` and control the robot using your keyboard.
robotont_teleop is now robotont_tutorials

2020-02-06 18:01 UTC, RValner commented on README.md
>  [![Build Status](https://travis-ci.org/robotont/robotont.svg?branch=master)](https://travis-ci.org/robotont/robotont)
Keep the badges in front of the readme ;)

2020-10-20 07:21 UTC, kruusamae commented
migrated to github.io

2020-10-20 07:21 UTC, closed without merging